import {
    attribute,
    autoGeneratedHashKey,
    table,
} from "@aws/dynamodb-data-mapper-annotations";
import {
    CustomType
} from "@aws/dynamodb-data-marshaller"

import { DynamoDB } from "aws-sdk";

const dateType: CustomType<Date> = {
    type: 'Custom',
    marshall: (input: Date): DynamoDB.AttributeValue => ({ S: input.toISOString() }),
    unmarshall: (persistedValue: DynamoDB.AttributeValue): Date => new Date(persistedValue.S!)
}
@table(process.env.TABLE_NAME || "Orders")
export class Order {
    @autoGeneratedHashKey()
        orderId?: string;
    @attribute()
        orderStatus?: string;
    @attribute()
        phoneNumber?: string;
    @attribute()
        pizzaSize?: string;
    @attribute()
        pizzaType?: string;
    @attribute()
        customer?: string;
    @attribute(dateType)
        createdAt?: Date;
    @attribute(dateType)
        updatedAt?: Date;
}